### ISSUE TITLE
Will not work in 4.23

### ISSUE THREAD

**Issue by ghost** [Ogniok/UE4GameJoltAPI#1]
I doubt this will work but I thought I should try. I am running the base project for testing and compilation but I get this error. 
```
c:\Users\donov\Documents\Unreal Projects\UE4GameJoltAPImaster\Source\GameJoltPlugin.Target.cs(19,12) : error CS0246: The type or namespace name 'UEBuildBinaryConfiguration' could not be found (are you missing a using directive or an assembly reference?)
c:\Users\donov\Documents\Unreal Projects\UE4GameJoltAPImaster\Source\GameJoltPluginEditor.Target.cs(19,12) : error CS0246: The type or namespace name 'UEBuildBinaryConfiguration' could not be found (are you missing a using directive or an assembly reference?)`
[GameJoltPlugin.log](https://github.com/Ogniok/UE4GameJoltAPI/files/3719922/GameJoltPlugin.log)
```

**Comment by ghost** [comment]
I understand this is wholly unsupported but if you could at least point me in the right direction in layman's terms that would be nice yes I am aware that this was created for 4.0.8 but there are two that were created a week apart and this is the only one with a GitHub and any semblance of support

**Comment by ghost** [comment]
As of right now, I have rebuilt the build.cs for the plugin so it will actually start to read it. It spits out a few errors that I will need to fix but it works. The next thing I am going to try and do is deal with the numerous errors elsewhere it is spitting in gamejoltAPI.cpp. I have moved the plugin to another project.
[MyProject3.log](https://github.com/Ogniok/UE4GameJoltAPI/files/3720128/MyProject3.log)

**Comment by ghost** [comment]
It is fine I found after a while something else.
